from __future__ import annotations

import csv
import html
import json
import math
import platform
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Optional

import numpy as np

from .coverage import coverage_audit
from .guidance import (
    build_experiment_ledger,
    build_factor_value_summary,
    recommend_neighbor_experiments,
)
from .ingest import (
    PROTOCOL_FIELDS,
    collect_records,
    filter_records,
    select_checkpoints,
    select_protocol_cohort,
)
from .pareto import (
    aggregate_configurations,
    load_baselines,
    rank_observed,
    resolve_em_target,
)
from .plots import plot_parameter_guidance
from .schema import (
    FACTORS,
    FACTOR_LABELS,
    METRICS,
    METRIC_LABELS,
    __version__,
    display_factor_value,
)


def _clean_owned_outputs(output_dir: Path) -> None:
    """Remove only files generated by this module that can become stale on rerun."""
    explicit = [
        output_dir / "model_diagnostics.json",
        output_dir / "tables" / "adjusted_main_effects.csv",
        output_dir / "tables" / "interaction_strengths.csv",
        output_dir / "tables" / "observed_pareto.csv",
        output_dir / "tables" / "predicted_candidates.csv",
    ]
    for path in explicit:
        path.unlink(missing_ok=True)
    figure_dir = output_dir / "figures"
    owned_prefixes = (
        "coverage",
        "model_diagnostics",
        "observed_parallel_coordinates",
        "observed_tradeoffs",
        "epoch_trajectories",
        "main_effects_",
        "interactions_",
        "parameter_guidance",
    )
    if figure_dir.is_dir():
        for path in figure_dir.iterdir():
            if path.is_file() and path.name.startswith(owned_prefixes):
                path.unlink()


def _serializable(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): _serializable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_serializable(item) for item in value]
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, (np.floating, float)):
        number = float(value)
        return number if math.isfinite(number) else None
    return value


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(_serializable(value), ensure_ascii=False, indent=2), encoding="utf-8"
    )


def _csv_cell(value: Any) -> Any:
    if value is None:
        return ""
    if isinstance(value, (dict, list, tuple, set)):
        return json.dumps(_serializable(value), ensure_ascii=False, sort_keys=True)
    return value


def write_csv(
    path: Path, rows: Iterable[dict[str, Any]], preferred: Iterable[str] = ()
) -> None:
    rows = list(rows)
    path.parent.mkdir(parents=True, exist_ok=True)
    keys = {key for row in rows for key in row}
    fields = [key for key in preferred if key in keys]
    fields.extend(sorted(keys - set(fields)))
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        if not fields:
            handle.write("")
            return
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: _csv_cell(row.get(field)) for field in fields})


def _fmt(value: Any, digits: int = 4) -> str:
    if value is None:
        return "—"
    try:
        number = float(value)
    except (TypeError, ValueError):
        return html.escape(str(value))
    return f"{number:.{digits}g}"


def _warning_list(warnings: list[str]) -> str:
    if not warnings:
        return '<p class="ok">没有发现数据读取或实验协议警告。</p>'
    return "<ul>" + "".join(f"<li>{html.escape(item)}</li>" for item in warnings) + "</ul>"


def _metric_cards(audit: dict[str, Any]) -> str:
    return "".join(
        f'<div class="metricCard"><b>{audit["metric_complete"].get(metric, 0)}</b>'
        f'<span>{html.escape(METRIC_LABELS[metric])}</span></div>'
        for metric in METRICS
    )


def _promising_table(recommendations: list[dict[str, Any]]) -> str:
    rows = []
    for item in recommendations:
        values = item.get("promising_values", [])
        value_text = ", ".join(
            display_factor_value(item["factor"], value) for value in values
        ) or "尚无可评分结果"
        rows.append(
            "<tr>"
            f'<td><strong>{html.escape(FACTOR_LABELS[item["factor"]])}</strong></td>'
            f"<td>{html.escape(value_text)}</td>"
            f'<td>{_fmt(item.get("best_score_median"), 3)}</td>'
            f'<td>{item.get("support_configurations", 0)}</td>'
            f'<td>{html.escape(str(item.get("evidence", "—")))}</td>'
            "</tr>"
        )
    return "".join(rows)


def _factor_summary_table(summary: list[dict[str, Any]]) -> str:
    rows = []
    for item in summary:
        status = "已实验" if item["status"] == "tested" else "未实验"
        rows.append(
            f'<tr class="{item["status"]}">'
            f'<td>{html.escape(FACTOR_LABELS[item["factor"]])}</td>'
            f'<td>{html.escape(display_factor_value(item["factor"], item["value"]))}</td>'
            f'<td><span class="pill {item["status"]}">{status}</span></td>'
            f'<td>{item["n_configurations"]}</td>'
            f'<td>{item["n_runs"]}</td>'
            f'<td>{_fmt(item.get("score_median"), 3)}</td>'
            f'<td>{_fmt(item.get("model_utility_median"), 5)}</td>'
            f'<td>{_fmt(item.get("forget_quality_median"), 5)}</td>'
            f'<td>{_fmt(item.get("forget_Q_A_gibberish_median"), 5)}</td>'
            f'<td>{_fmt(item.get("exact_memorization_median"), 5)}</td>'
            f'<td>{html.escape(str(item.get("evidence", "—")))}</td>'
            "</tr>"
        )
    return "".join(rows)


def _top_observed_table(observed: list[dict[str, Any]], limit: int = 5) -> str:
    rows = [row for row in observed if row.get("observed_score") is not None][:limit]
    if not rows:
        return '<tr><td colspan="12">当前没有足够的指标值用于相对评分。</td></tr>'
    return "".join(
        "<tr>"
        f"<td>{index}</td>"
        + "".join(f"<td>{_fmt(row.get(factor), 5)}</td>" for factor in FACTORS)
        + f'<td><strong>{_fmt(row.get("observed_score"), 3)}</strong></td>'
        + f'<td>{row.get("score_metrics_used", 0)}/{row.get("score_metrics_expected", 0)}</td>'
        + "".join(f"<td>{_fmt(row.get(metric), 5)}</td>" for metric in METRICS)
        + "</tr>"
        for index, row in enumerate(rows, start=1)
    )


def _next_experiment_table(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return (
            '<tr><td colspan="8">没有生成邻域建议：需要至少一个具有可评分指标的已实验配置。</td></tr>'
        )
    return "".join(
        "<tr>"
        f'<td><strong>{row["priority"]}</strong></td>'
        + "".join(f"<td>{_fmt(row.get(factor), 5)}</td>" for factor in FACTORS)
        + f'<td>{html.escape(str(row.get("primary_change", "—")))}</td>'
        + f'<td>{row.get("neighbor_support", 1)}</td>'
        + f'<td>{_fmt(row.get("best_source_score"), 3)}</td>'
        + "</tr>"
        for row in rows
    )


def build_html_report(
    output_path: Path,
    observed: list[dict[str, Any]],
    ledger: list[dict[str, Any]],
    factor_summary: list[dict[str, Any]],
    factor_recommendations: list[dict[str, Any]],
    next_experiments: list[dict[str, Any]],
    audit: dict[str, Any],
    baselines: dict[str, Any],
    em_target: Optional[float],
    guidance_image: Optional[str],
    warnings: list[str],
    config: dict[str, Any],
    provenance: dict[str, Any],
) -> None:
    ledger_json = json.dumps(_serializable(ledger), ensure_ascii=False).replace("</", "<\\/")
    factors_json = json.dumps(list(FACTORS))
    metrics_json = json.dumps(list(METRICS))
    labels_json = json.dumps({**FACTOR_LABELS, **METRIC_LABELS}, ensure_ascii=False)
    filters = config.get("filters", {})
    context = " · ".join(
        f"{key}={value}" for key, value in filters.items() if value is not None
    )
    generated = datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")
    counts = provenance["counts"]
    missing_count = sum(row.get("status") == "missing" for row in ledger)
    other_checkpoint_count = sum(row.get("status") == "other_checkpoint" for row in ledger)
    empty_html = ""
    if not observed:
        empty_html = f"""
        <div class="emptyState">
          <h2>当前筛选条件下没有可用于比较的实验结果</h2>
          <p>扫描到 {counts['all_records']} 条评估记录，筛选后 {counts['filtered_records']} 条，满足当前 checkpoint 规则的记录为 {counts['selected_checkpoint_records']} 条。</p>
          <p>扫描目录：<code>{html.escape(provenance['result_root'])}</code></p>
          <p>下方实验台账仍会列出规划组合；请优先核对结果根目录、模型名、split 和 epoch/checkpoint 规则。</p>
        </div>"""
    image_html = (
        f'<img class="guidance" src="{html.escape(guidance_image)}" alt="Observed parameter guidance">'
        if guidance_image
        else '<p class="muted">现有指标不足，暂不绘制取值趋势图，避免产生空图。</p>'
    )
    html_text = f"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PALU 稀疏超参数实验记录</title>
<style>
:root {{ --blue:#0072B2; --orange:#E69F00; --green:#009E73; --ink:#17212b; --muted:#607080; --line:#d9e1e8; --paper:#fff; --wash:#f5f7f9; --missing:#eef1f4; }}
* {{ box-sizing:border-box; }}
body {{ margin:0; color:var(--ink); background:var(--wash); font:14px/1.55 Arial,"PingFang SC","Microsoft YaHei",sans-serif; }}
header {{ color:white; background:#073763; padding:28px max(20px,calc((100vw - 1160px)/2)); }}
header h1 {{ margin:0 0 8px; font-size:27px; }} header p {{ margin:3px 0; opacity:.9; }}
main {{ max-width:1160px; margin:auto; padding:20px; }}
section {{ background:var(--paper); border:1px solid var(--line); border-radius:10px; padding:20px; margin-bottom:16px; }}
h2 {{ margin:0 0 12px; font-size:20px; }} h3 {{ margin:20px 0 9px; font-size:16px; }}
.cards,.metricCards {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:10px; }}
.card,.metricCard {{ border:1px solid var(--line); border-radius:8px; padding:12px; background:#fafcfd; }}
.card b,.metricCard b {{ display:block; font-size:22px; }} .card span,.metricCard span,.muted,.note {{ color:var(--muted); font-size:12px; }}
.metricCard b {{ font-size:18px; }} .emptyState {{ border-left:5px solid var(--orange); background:#fff8e8; padding:15px 18px; margin-bottom:16px; }}
.emptyState h2 {{ font-size:18px; }} .ok {{ color:var(--green); }}
.tableWrap {{ overflow:auto; max-height:560px; border:1px solid var(--line); border-radius:6px; }}
table {{ width:100%; border-collapse:collapse; font-size:12px; }} th,td {{ padding:8px 9px; border-bottom:1px solid var(--line); white-space:nowrap; text-align:left; }}
th {{ position:sticky; top:0; z-index:1; background:#eaf0f6; }} tr:hover {{ background:#f3f8fb; }} tr.missing {{ color:#7b8792; }}
.pill {{ display:inline-block; border-radius:12px; padding:2px 8px; }} .pill.tested {{ color:#006b45; background:#dff3e8; }} .pill.missing {{ color:#68737d; background:var(--missing); }}
.guidance {{ display:block; max-width:100%; margin:8px auto; border:1px solid var(--line); }}
.controls {{ display:flex; flex-wrap:wrap; gap:9px; margin:10px 0; }} label {{ color:var(--muted); font-size:12px; }} select {{ display:block; min-width:125px; padding:6px; border:1px solid var(--line); border-radius:5px; background:white; }}
code {{ background:#eef2f5; padding:2px 5px; border-radius:4px; }}
@media(max-width:700px) {{ main {{ padding:10px; }} section {{ padding:14px; }} header {{ padding:22px 16px; }} }}
</style>
</head>
<body>
<header>
  <h1>PALU 稀疏超参数实验记录与取值指引</h1>
  <p>{html.escape(context or '未设置过滤条件')}</p>
  <p>生成时间 {html.escape(generated)} · 模块 v{__version__}</p>
</header>
<main>
{empty_html}
<section>
  <h2>当前实验概况</h2>
  <div class="cards">
    <div class="card"><b>{counts['selected_checkpoint_records']}</b><span>符合 checkpoint 规则的记录</span></div>
    <div class="card"><b>{len(observed)}</b><span>已实验参数组合</span></div>
    <div class="card"><b>{missing_count}</b><span>规划空间中尚未实验</span></div>
    <div class="card"><b>{other_checkpoint_count}</b><span>有运行但缺少目标 checkpoint</span></div>
  </div>
  <h3>四项指标的实际可用数量</h3>
  <div class="metricCards">{_metric_cards(audit)}</div>
  <p class="note">这里统计实际读取到的值；不会为了填满图表而插补缺失指标。</p>
</section>

<section>
  <h2>从已有结果看，哪些取值更值得继续</h2>
  <p>综合分数是四项指标在<strong>当前已有实验内部</strong>的等权方向化百分位均值。少于 2 条记录或覆盖不足一半的指标不进入综合分数；单条记录缺失的参与指标按 0 分保守处理。</p>
  <div class="tableWrap"><table><thead><tr><th>参数</th><th>当前较有希望的取值</th><th>最佳中位分数</th><th>支持配置数</th><th>证据量</th></tr></thead><tbody>{_promising_table(factor_recommendations)}</tbody></table></div>
  {image_html}
  <p class="note">这是稀疏、非平衡实验下的描述性定位，用来缩小下一轮搜索范围；不能解释为单个参数的因果效应。</p>
</section>

<section>
  <h2>当前表现较好的已实验配置</h2>
  <div class="tableWrap"><table><thead><tr><th>排名</th><th>lr</th><th>alpha</th><th>top_k</th><th>first_n</th><th>综合分数</th><th>参与指标</th><th>MU</th><th>FQ</th><th>Fluency</th><th>EM</th></tr></thead><tbody>{_top_observed_table(observed)}</tbody></table></div>
  <p class="note">排名仅比较已有配置；综合分数不是论文指标，也不代表已经找到全局最优。</p>
</section>

<section>
  <h2>每个参数取值的现有证据</h2>
  <div class="tableWrap"><table><thead><tr><th>参数</th><th>取值</th><th>状态</th><th>配置数</th><th>运行数</th><th>综合分数中位数</th><th>MU 中位数</th><th>FQ 中位数</th><th>Fluency 中位数</th><th>EM 中位数</th><th>证据量</th></tr></thead><tbody>{_factor_summary_table(factor_summary)}</tbody></table></div>
</section>

<section>
  <h2>建议优先补做的少量实验</h2>
  <p>只列出当前高分配置的<strong>单参数相邻取值</strong>，其余三个参数保持不变；不要求遍历完整网格。</p>
  <div class="tableWrap"><table><thead><tr><th>优先级</th><th>lr</th><th>alpha</th><th>top_k</th><th>first_n</th><th>相对最高排名来源的单项变化</th><th>相邻高分来源数</th><th>来源分数</th></tr></thead><tbody>{_next_experiment_table(next_experiments)}</tbody></table></div>
  <p class="note">这些是低成本的局部验证建议，不是模型预测出的结果。</p>
</section>

<section>
  <h2>实验台账：已做与未做</h2>
  <p>默认显示已实验组合；切换状态可直接查看缺失组合。完整台账同时保存为 <code>tables/experiment_ledger.csv</code>。</p>
  <div class="controls">
    <label>状态<select id="statusFilter"><option value="tested">已实验</option><option value="other_checkpoint">有运行但缺目标 checkpoint</option><option value="missing">未实验</option><option value="*">全部</option></select></label>
    <label>lr<select id="f_lr"></select></label><label>alpha<select id="f_alpha"></select></label><label>top_k<select id="f_top_k"></select></label><label>first_n<select id="f_first_n"></select></label>
  </div>
  <p id="ledgerCount" class="note"></p>
  <div class="tableWrap"><table id="ledgerTable"></table></div>
</section>

<section>
  <h2>数据边界与读取警告</h2>
  {_warning_list(warnings)}
  <p class="note">Exact memorization 目标：{_fmt(em_target, 6)}；优先使用 Retain baseline。FQ 是 KS 检验 p 值，不是遗忘百分比。</p>
</section>

<section>
  <h2>可复用记录文件</h2>
  <p><code>tables/observed_configurations.csv</code> 保存已有结果，<code>tables/parameter_value_summary.csv</code> 保存各取值摘要，<code>tables/recommended_next_experiments.csv</code> 保存少量邻域建议，<code>tables/experiment_ledger.csv</code> 保存完整实验状态。</p>
</section>
</main>
<script>
const ledger={ledger_json};
const factors={factors_json};
const metrics={metrics_json};
const labels={labels_json};
function esc(value){{return String(value??'—').replace(/[&<>"']/g,ch=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[ch]));}}
function fmt(value){{if(value===null||value===undefined||value==='')return '—';if(typeof value==='number')return Number(value).toPrecision(5);return esc(value);}}
function unique(field){{return [...new Set(ledger.map(row=>String(row[field])))].sort((a,b)=>Number(a)-Number(b));}}
function fill(id,values){{const select=document.getElementById(id);select.innerHTML='<option value="*">全部</option>';values.forEach(value=>select.add(new Option(value,value)));}}
factors.forEach(factor=>fill('f_'+factor,unique(factor)));
function renderLedger(){{
  const status=document.getElementById('statusFilter').value;
  const rows=ledger.filter(row=>(status==='*'||row.status===status)&&factors.every(factor=>{{const value=document.getElementById('f_'+factor).value;return value==='*'||String(row[factor])===value;}}));
  document.getElementById('ledgerCount').textContent='当前显示 '+rows.length+' 个组合';
  const columns=['status',...factors,'n_runs','available_epochs',...metrics,'observed_score'];
  const statusLabel={{tested:'已实验',missing:'未实验',other_checkpoint:'有运行但缺目标 checkpoint',tested_outside_space:'空间外已实验'}};
  document.getElementById('ledgerTable').innerHTML='<thead><tr>'+columns.map(column=>'<th>'+esc(labels[column]||column)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr class="'+esc(row.status)+'">'+columns.map(column=>'<td>'+(column==='status'?esc(statusLabel[row.status]||row.status):fmt(row[column]))+'</td>').join('')+'</tr>').join('')+'</tbody>';
}}
document.querySelectorAll('select').forEach(select=>select.addEventListener('change',renderLedger));renderLedger();
</script>
</body></html>"""
    output_path.write_text(html_text, encoding="utf-8")


def run_analysis(
    result_root: Path,
    config: dict[str, Any],
    output_dir: Path,
    repo_root: Path,
) -> dict[str, Any]:
    _clean_owned_outputs(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    tables_dir = output_dir / "tables"
    figures_dir = output_dir / "figures"
    tables_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)

    all_records, warnings = collect_records(result_root)
    filtered = filter_records(all_records, config)
    cohort_records, protocol_excluded, protocol_cohorts = select_protocol_cohort(
        filtered, config
    )
    if protocol_excluded:
        warnings.append(
            f"excluded {len(protocol_excluded)} rows outside the largest protocol cohort; "
            "see tables/protocol_cohorts.csv"
        )
    selected = select_checkpoints(cohort_records, config)
    if filtered and not selected:
        checkpoint = config.get("checkpoint", {})
        epochs = sorted(
            {row.get("epoch") for row in cohort_records if row.get("epoch") is not None}
        )
        warnings.append(
            f"no rows matched checkpoint policy {checkpoint}; available epochs: "
            + ", ".join(str(value) for value in epochs)
        )

    observed = aggregate_configurations(selected)
    baselines, baseline_warnings = load_baselines(str(repo_root), config)
    warnings.extend(baseline_warnings)
    em_target = resolve_em_target(config, baselines)
    if em_target is None:
        warnings.append(
            "Retain exact_memorization baseline is unavailable; lower EM is treated as better when EM participates"
        )
    observed = rank_observed(observed, config, em_target)
    audit = coverage_audit(observed, config)
    factor_summary, factor_recommendations = build_factor_value_summary(
        observed, config
    )
    ledger = build_experiment_ledger(observed, config, cohort_records)
    next_experiments = recommend_neighbor_experiments(observed, ledger, config)

    preferred = [
        "status",
        *FACTORS,
        "epoch",
        *METRICS,
        "observed_score",
        "score_metrics_used",
        "score_metrics_expected",
        "n_runs",
        "pareto_observed",
    ]
    write_csv(tables_dir / "all_filtered_checkpoints.csv", cohort_records, preferred)
    write_csv(tables_dir / "selected_checkpoint_rows.csv", selected, preferred)
    write_csv(tables_dir / "observed_configurations.csv", observed, preferred)
    write_csv(tables_dir / "parameter_value_summary.csv", factor_summary)
    write_csv(
        tables_dir / "recommended_next_experiments.csv", next_experiments, preferred
    )
    write_csv(tables_dir / "experiment_ledger.csv", ledger, preferred)
    write_csv(
        tables_dir / "missing_combinations.csv",
        [row for row in ledger if row.get("status") == "missing"],
        preferred,
    )
    write_csv(
        tables_dir / "outside_search_space.csv", audit["outside_search_space"], preferred
    )
    write_csv(
        tables_dir / "protocol_cohorts.csv",
        protocol_cohorts,
        [*PROTOCOL_FIELDS, "n_rows"],
    )
    write_csv(
        tables_dir / "excluded_protocol_rows.csv", protocol_excluded, preferred
    )
    write_json(output_dir / "coverage_audit.json", audit)

    provenance = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "module_version": __version__,
        "python": platform.python_version(),
        "result_root": str(result_root.resolve()),
        "repo_root": str(repo_root.resolve()),
        "config": config,
        "baselines": baselines,
        "exact_memorization_target": em_target,
        "counts": {
            "all_records": len(all_records),
            "filtered_records": len(filtered),
            "protocol_cohort_records": len(cohort_records),
            "selected_checkpoint_records": len(selected),
            "observed_configurations": len(observed),
            "recommended_next_experiments": len(next_experiments),
        },
        "warnings": warnings,
    }
    write_json(output_dir / "provenance.json", provenance)

    guidance_paths = plot_parameter_guidance(
        factor_summary, figures_dir / "parameter_guidance", config
    )
    guidance_image = None
    for raw_path in guidance_paths:
        path = Path(raw_path)
        if path.suffix.lower() == ".png":
            guidance_image = path.relative_to(output_dir).as_posix()
            break
    build_html_report(
        output_dir / "report.html",
        observed,
        ledger,
        factor_summary,
        factor_recommendations,
        next_experiments,
        audit,
        baselines,
        em_target,
        guidance_image,
        warnings,
        config,
        provenance,
    )
    manifest = {
        "report": str((output_dir / "report.html").resolve()),
        "provenance": str((output_dir / "provenance.json").resolve()),
        "tables": str(tables_dir.resolve()),
        "figures": str(figures_dir.resolve()),
        "counts": provenance["counts"],
        "warnings": warnings,
    }
    write_json(output_dir / "manifest.json", manifest)
    return manifest
